name: denaro # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2023.5.0' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: denaro
summary: Manage your personal finances
description: |
  A personal finance manager
icon: NickvisionMoney.Shared/Resources/org.nickvision.money.png
source-code: https://github.com/nlogozzo/NickvisionMoney
issues: https://github.com/nlogozzo/NickvisionMoney/issues
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
layout:
  /usr/lib/org.nickvision.money:
    symlink: $SNAP/usr/lib/org.nickvision.money
  /usr/share/org.nickvision.money:
    symlink: $SNAP/usr/share/org.nickvision.money
parts:
  denaro:
    # See 'snapcraft plugins'
    plugin: nil
    source: .
    build-packages:
      - blueprint-compiler
      - wget
    override-pull: |
      craftctl default
      wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      chmod +x ./dotnet-install.sh
      ./dotnet-install.sh --channel 7.0
    override-build: |
      export DOTNET_ROOT=$HOME/.dotnet
      export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools:$HOME/.cargo/bin
      cd $CRAFT_PART_SRC_WORK
      dotnet tool restore
      dotnet cake --target=Publish --prefix=/usr --ui=gnome --self-contained
      dotnet cake --target=Install --destdir=$CRAFT_PRIME
    parse-info: [ usr/share/appdata/org.nickvision.money.metainfo.xml ]
apps:
  denaro:
    command: usr/bin/org.nickvision.money
    desktop: usr/share/applications/org.nickvision.money.desktop
    extensions: [gnome]
    common-id: org.nickvision.money
    plugs:
      - home
      - removable-media
