name: denaro 
base: core22
adopt-info: denaro
grade: stable
confinement: strict
compression: lzo

package-repositories:
 - type: apt
   ppa: ubuntu-toolchain-r/test
   priority: always

lint:
  ignore:
    - classic
    - library

parts:
  build-deps:
    plugin: nil
    build-packages:
      - g++-13
      - gcc-13
      - libjsoncpp-dev
      - libidn-dev
      - libjpeg-dev
      - libtiff-dev
      - libpng-dev
      - libfreetype-dev
      - libblas-dev 
      - liblapack-dev
    override-build: |
      cp -r ${CRAFT_PART_SRC}/ ${CRAFT_STAGE}/
      update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13

  deps:
    after: [build-deps]
    plugin: nil
    stage-packages:
      - libjsoncpp25
      - libboost-date-time1.74.0
      - libstdc++6
      - gnuplot
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libstdc++*.so*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libjsoncpp*
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_date_time.so.1.74.0
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libboost_thread.so.1.74.0

  maddy:
    after: [build-deps]
    source: https://github.com/progsource/maddy.git
    source-tag: '1.3.0'
    plugin: dump
    source-depth: 1
    override-prime: '' 

  libnick:
    after: [maddy, build-deps]
    source: https://github.com/nickvisionapps/libnick.git
    source-tag: '2024.5.0'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DBUILD_TESTING=OFF
      - -DCMAKE_BUILD_TYPE=Release
    build-environment:
      - CPLUS_INCLUDE_PATH: ${CRAFT_STAGE}/include
    build-packages:
      - libboost-all-dev
      - libssl-dev
      - uuid-dev
    override-prime: ''

  libxmlplusplus:
    after: [build-deps]
    source: https://github.com/libxmlplusplus/libxmlplusplus.git
    source-tag: '5.2.0'
    source-depth: 1
    plugin: meson
    build-packages:
      - libicu-dev
    meson-parameters:
      - --prefix=/usr
      - -Dmaintainer-mode=false
    prime:
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/libxml++-5.0*.so*

  podofo:
    after: [build-deps]
    source: https://github.com/podofo/podofo.git
    source-tag: '0.10.3'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DPODOFO_BUILD_TEST=OFF
      - -DPODOFO_BUILD_EXAMPLES=OFF
    build-environment:
      - CPLUS_INCLUDE_PATH: ${CRAFT_STAGE}/include

  rapidcsv:
    after: [build-deps]
    source: https://github.com/d99kris/rapidcsv.git
    source-tag: 'v8.82'
    source-depth: 1
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
    build-environment:
      - CPLUS_INCLUDE_PATH: ${CRAFT_STAGE}/include

  denaro:
    after: [build-deps, maddy, libnick, libxmlplusplus, matplotplusplus, podofo, rapidcsv]
    plugin: cmake
    source: .
    build-snaps:
      - cmake
      - blueprint-compiler
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/snap/denaro/current/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_TESTING=OFF
    stage-packages:
      - libstdc++6
    build-environment:
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/cmake${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
    parse-info: [usr/share/metainfo/org.nickvision.money.metainfo.xml]
    organize:
      snap/denaro/current: .

slots:
  denaro:
    interface: dbus
    bus: session
    name: org.nickvision.money

apps:
  denaro:
    command: usr/lib/org.nickvision.money/org.nickvision.money.gnome
    desktop: usr/share/money/org.nickvision.money.desktop
    common-id: org.nickvision.money
    extensions: [gnome]
    plugs:
      - unity7
      - network
      - network-status
