on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "review_requested", "ready_for_review" ]
  workflow_dispatch:
name: Windows
permissions:
  id-token: write
  contents: read
env:
  BUILD_TYPE: Release
  GITHUB_ACTIONS: true
  VCPKG_ROOT: ${{github.workspace}}/vcpkg
jobs:
  build:
    name: "Build on x64"
    runs-on: windows-latest
    if: ${{ github.event.pull_request.user.login != 'weblate' }}
    steps:
      - name: "Checkout"  
        uses: actions/checkout@v4
      - name: "Setup Environment"
        run: mkdir build
      - name: "Vcpkg"
        uses: johnwason/vcpkg-action@v5
        id: vcpkg
        with:
          pkgs: libnick matplotplusplus podofo
          triplet: x64-windows
          cache-key: windows-latest
          revision: a58271747fd00c2f53342f20c2d9fd944fbaa386
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build"
        working-directory: ${{github.workspace}}/build
        run: |
          cmake -G "Visual Studio 17 2022" ..
          cmake --build . --config ${{env.BUILD_TYPE}}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{github.workspace}}/build/org.nickvision.money.winui/Release
          name: Windows-x64-${{env.BUILD_TYPE}}